### ISSUE TITLE
How to only post the url to the issue instead of the body?

### ISSUE THREAD

**Issue by ReenigneArcher** [git-for-windows/rss-to-issues#53]
```yml
jobs:
  rss-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: RSS to issues
        uses: git-for-windows/rss-to-issues@v0
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          feed: https://lizardbyte.github.io/feed.xml
          character-limit: 0
          dry-run: false
          max-age: 48h
          labels: blog
```

Results in:
![image](https://github.com/user-attachments/assets/6576322d-9b4e-437e-a61d-cedc7ec9f032)

But I would like only the url. Is it possible?

Looking at the code it looks like this would need to be adjusted:

https://github.com/git-for-windows/rss-to-issues/blob/668f251cb387458e9adc6a010ee0655675c90209/index.js#L94-L97

Would you accept a PR to either:

1. Have a value of 0 to not have anything except the url
2. Have a negative value (e.g. -1) to not have anything except the url
3. Add an input option to only show the url
